version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:latest
    container_name: airflow-webserver
    restart: always
    depends_on:
      - postgres
      - airflow-scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__TEST_CONNECTION: 'Enabled'
      AIRFLOW__CORE__DEFAULT_TIMEZONE: 'Asia/Jakarta'
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./dags/helpers:/opt/airflow/dags/helpers
      - ./data:/opt/airflow/data
      - ./data/sample_data.json:/opt/airflow/data/sample_data.json
      - ./requirements.txt:/requirements.txt
    command: bash -c "pip install -r /requirements.txt && airflow db upgrade && airflow webserver"

  airflow-scheduler:
    image: apache/airflow:latest
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__TEST_CONNECTION: 'Enabled'
      AIRFLOW__CORE__DEFAULT_TIMEZONE: 'Asia/Jakarta'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./dags/helpers:/opt/airflow/dags/helpers
      - ./data:/opt/airflow/data
      - ./data/sample_data.json:/opt/airflow/data/sample_data.json
      - ./requirements.txt:/requirements.txt
    command: bash -c "pip install -r /requirements.txt && airflow db upgrade && airflow scheduler"

  airflow-init:
    image: apache/airflow:latest
    container_name: airflow-init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__TEST_CONNECTION: 'Enabled'
      AIRFLOW__CORE__DEFAULT_TIMEZONE: 'Asia/Jakarta'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./dags/helpers:/opt/airflow/dags/helpers
      - ./data:/opt/airflow/data
      - ./data/sample_data.json:/opt/airflow/data/sample_data.json
      - ./requirements.txt:/requirements.txt
    command: bash -c "pip install -r /requirements.txt && airflow db upgrade && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"

  spark:
    image: bitnami/spark:latest
    container_name: spark
    volumes:
      - ./helpers:/opt/spark/helpers
      - ./data:/opt/spark/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity

volumes:
  postgres_data:
