FROM apache/airflow:2.7.3-python3.11

USER root

RUN apt-get update && apt-get install -y openjdk-11-jdk procps

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:$PATH"

USER airflow

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
